builds:
  - goos:
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
brew:
  github:
    owner: miyazi777
    name: homebrew-git-desc
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  description: "Git descrption CLI Tool"
  homepage: "https://github.com/miyazi777/git-desc"
  install: |
    bin.install Dir['git-desc']
  test: |
    system "#{bin}/git-desc"
