version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "A first hello"
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "A first hello"
