version: 2.0
jobs:
  setup:
    working_director: ~/workspace
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: github.com/mitchellh/go-homedir install
          command: go get github.com/mitchellh/go-homedir
      - run:
          name: github.com/spf13/cobra install
          command: go get github.com/spf13/cobra
      - run:
          name: github.com/spf13/viper install
          command: go get github.com/spf13/viper
      - run:
          name: github.com/cheynewallace/tabby install
          command: go get github.com/cheynewallace/tabby
      - run:
          name: github.com/stretchr/testify install
          command: go get github.com/stretchr/testify
  test:
    working_director: ~/workspace
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Test
          command: go test -v -cover -coverprofile /tmp/cover.out ./...
      - run:
          name: Generate code coverage
          command: go tool cover -html=/tmp/cover.out -o /tmp/cover.html
      - store_artifacts:
          path: /tmp/cover.html
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
